project:
  type: book
  output-dir: docs

book:
  page-navigation: true
  title: "Quatro for amsmath LaTeX users"
  site-url: "https://nmfs-opensci.github.io/quarto-amsmath" 
  repo-url: "https://github.com/nmfs-opensci/quarto-amsmath"
  repo-actions: [edit, source, issue]
  downloads: [pdf]
  search: true
  chapters:
    - index.qmd
    - background.qmd
    - yaml.qmd
    - numbered_equations.qmd

format:
  html:
    include-in-header: mathjax.html
  pdf: default
# Don't use this. Breaks numbering (Aug 2024)
#    html-math-method:
#      method: mathjax
#      url: "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
      
