project:
  type: book
  output-dir: docs

book:
  title: "Quatro for amsmath LaTeX users"
  chapters:
    - index.qmd
    - background.qmd
    - yaml.qmd
    - numbered_equations.qmd

format:
  html:
    include-in-header: mathjax.html
  pdf: default
# Don't use this. Breaks numbering (Aug 2024)
#    html-math-method:
#      method: mathjax
#      url: "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
      
