project:
  type: book

book:
  title: "delete-me"
  chapters:
    - index.qmd
    - intro.qmd

format:
  html:
    include-in-header: mathjax.html
    html-math-method:
      method: mathjax
      url: "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
      
