project:
  type: book

book:
  title: "delete-me"
  chapters:
    - index.qmd
    - intro.qmd

format:
  html:
    include-in-header: mathjax.html
  pdf: default
# Don't use this. Breaks numbering (Aug 2024)
#    html-math-method:
#      method: mathjax
#      url: "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
      
